### ISSUE TITLE
Slave-Lib?

### ISSUE THREAD

**Issue by vizv** [master801/BetterFonts#3]
Hi, I'm trying to build this on branch 1.8-substitution.
However I miss org.slave.lib stuffs.

**Comment by secretdataz** [comment]
It used to be in @master801's repo. I'm not sure if he removed it.

**Comment by master801** [comment]
@vizv @secretdataz I did remove the Slave-Lib repository.

I'm going to upload a build of it soon once I get Gradle to build like I want it to.

**Comment by master801** [comment]
Sooo.... question, what version should I update the mod to next?

I know that 1.8 is outdated, so should I update it to something higher besides 1.8.9 (already working on that)?

**Comment by secretdataz** [comment]
Ah, I'm not sure if the renderer has changed again in 1.9 or not, but updating to latest version with stable forge would be the best bet. (or latest version with manual decompilation if you wanna have an headache.)

**Comment by master801** [comment]
@secretdataz Yeah, the rendering changed in 1.8.9, so much that I can't get it working really. Coloring is mainly the issue with it though.
